config:
  clients:
    - url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push
      tenant_id: fake

tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule