apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "invoice-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ include "invoice-api.fullname" . }}
  namespaceSelector:
    matchNames:
      - invoice
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
